# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
- repo: self

variables:
  AzureServiceConnection: 'Azure'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    azureSubscription: 'Azure'
    command: 'buildAndPush'
    containerRegistry: 'bhjbcontainer.azurecr.io'
    repository: 'gprojectsazbhjbassessmenttest'
    Dockerfile: '$(Build.SourcesDirectory)/aspnet-core-dotnet-core/Dockerfile'