# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  AzureServiceConnection: 'Azure'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  inputs:
    azureSubscription: 'Azure'
    command: 'buildAndPush'
    containerRegistry: 'bhjbcontainer'
    repository: 'gprojectsazbhjbassessment'
    Dockerfile: '**/Dockerfile'